<?xml version="1.0" encoding="UTF-8"?>
<databrowser>
    <title></title>
    <update_period>0.1</update_period>
    <scroll_step>1</scroll_step>
    <period>300.0</period>
    <ring_size>5000</ring_size>
    <start>-15 min</start>
    <end>now</end>
    <pvlist>
        <pv>
            <display_name>BPM1:XPOS_RD</display_name>
            <visible>true</visible>
            <name>BPM1:XPOS_RD</name>
            <axis>0</axis>
            <color><red>172</red><green>47</green><blue>117</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM2:XPOS_RD</display_name>
            <visible>true</visible>
            <name>BPM2:XPOS_RD</name>
            <axis>0</axis>
            <color><red>192</red><green>67</green><blue>251</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM3:XPOS_RD</display_name>
            <visible>true</visible>
            <name>BPM3:XPOS_RD</name>
            <axis>0</axis>
            <color><red>195</red><green>103</green><blue>9</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM1:YPOS_RD</display_name>
            <visible>true</visible>
            <name>BPM1:YPOS_RD</name>
            <axis>1</axis>
            <color><red>211</red><green>21</green><blue>242</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM2:YPOS_RD</display_name>
            <visible>true</visible>
            <name>BPM2:YPOS_RD</name>
            <axis>1</axis>
            <color><red>36</red><green>87</green><blue>70</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM3:YPOS_RD</display_name>
            <visible>true</visible>
            <name>BPM3:YPOS_RD</name>
            <axis>1</axis>
            <color><red>216</red><green>88</green><blue>140</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BCM:PKAVG_RD</display_name>
            <visible>true</visible>
            <name>BCM:PKAVG_RD</name>
            <axis>2</axis>
            <color><red>58</red><green>193</green><blue>230</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>FC:PKAVG_RD</display_name>
            <visible>true</visible>
            <name>FC:PKAVG_RD</name>
            <axis>2</axis>
            <color><red>39</red><green>87</green><blue>174</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM1:PHASE_RD</display_name>
            <visible>true</visible>
            <name>BPM1:PHASE_RD</name>
            <axis>3</axis>
            <color><red>88</red><green>81</green><blue>165</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM2:PHASE_RD</display_name>
            <visible>true</visible>
            <name>BPM2:PHASE_RD</name>
            <axis>4</axis>
            <color><red>25</red><green>77</green><blue>72</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>BPM3:PHASE_RD</display_name>
            <visible>true</visible>
            <name>BPM3:PHASE_RD</name>
            <axis>5</axis>
            <color><red>9</red><green>148</green><blue>115</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X1:I_CSET</display_name>
            <visible>true</visible>
            <name>X1:I_CSET</name>
            <axis>6</axis>
            <color><red>208</red><green>243</green><blue>197</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X1:I_RD</display_name>
            <visible>true</visible>
            <name>X1:I_RD</name>
            <axis>6</axis>
            <color><red>208</red><green>243</green><blue>197</blue></color>
            <trace_type>DASHED</trace_type>
            <linewidth>1</linewidth>
            <line_style>DASH</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X2:I_CSET</display_name>
            <visible>true</visible>
            <name>X2:I_CSET</name>
            <axis>6</axis>
            <color><red>254</red><green>79</green><blue>175</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X2:I_RD</display_name>
            <visible>true</visible>
            <name>X2:I_RD</name>
            <axis>6</axis>
            <color><red>254</red><green>79</green><blue>175</blue></color>
            <trace_type>DASHED</trace_type>
            <linewidth>1</linewidth>
            <line_style>DASH</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X3:I_CSET</display_name>
            <visible>true</visible>
            <name>X3:I_CSET</name>
            <axis>6</axis>
            <color><red>192</red><green>82</green><blue>99</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X3:I_RD</display_name>
            <visible>true</visible>
            <name>X3:I_RD</name>
            <axis>6</axis>
            <color><red>192</red><green>82</green><blue>99</blue></color>
            <trace_type>DASHED</trace_type>
            <linewidth>1</linewidth>
            <line_style>DASH</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X4:I_CSET</display_name>
            <visible>true</visible>
            <name>X4:I_CSET</name>
            <axis>6</axis>
            <color><red>216</red><green>177</green><blue>243</blue></color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <line_style>SOLID</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
        <pv>
            <display_name>X4:I_RD</display_name>
            <visible>true</visible>
            <name>X4:I_RD</name>
            <axis>6</axis>
            <color><red>216</red><green>177</green><blue>243</blue></color>
            <trace_type>DASHED</trace_type>
            <linewidth>1</linewidth>
            <line_style>DASH</line_style>
            <point_type>NONE</point_type>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
        </pv>
    </pvlist>
</databrowser>